apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hx676unox-python
  janus-idp.io/tekton: hx676unox-python
  backstage.io/kubernetes-id: hx676unox-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hx676unox-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
